services:
  # ========================================================
  # GPU Production Service
  # ========================================================
  gpu:
    restart: unless-stopped
    profiles: ["gpu"]
    build:
      context: ..
      dockerfile: docker/Dockerfile.gpu
      target: prod
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    container_name: vieneu-tts-gpu
    ports:
      - "${PORT}:7860"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - /opt/vieneu-caches/huggingface:/root/.cache/huggingface
      - ../output_audio:/workspace/output_audio
    env_file:
      - ../.env
    networks:
      - default
      - traefik_cloudflare
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vieneu-tts.rule=Host(`voice-tts.nguyentracthanh.site`)"
      - "traefik.http.routers.vieneu-tts.entrypoints=web"
      - "traefik.http.routers.vieneu-tts.middlewares=vieneu-tts-auth"
      - "traefik.http.middlewares.vieneu-tts-auth.basicauth.users=thanhnt.usth@gmail.com:$$apr1$$U3w5MtC3$$/cmb6IAqFn.BR2EdvueEx0"
      - "traefik.http.services.vieneu-tts.loadbalancer.server.port=7860"
      - "traefik.docker.network=traefik_cloudflare"

networks:
  traefik_cloudflare:
    external: true
